services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - auth-service
      - user-service
      - order-service
    networks:
      - innowise_network

  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      USERS_DB_HOST: localhost
      USERS_DB_DATABASE: user_db
      USERS_DB_USERNAME: postgres
      USERS_DB_PASSWORD: postgres
      REDIS_HOST: users_redis
      REDIS_DATABASE: 0
    depends_on:
      - users_db
      - users_redis
    networks:
      - innowise_network

  users_db:
    container_name: users_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${USERS_DB_USERNAME}
      POSTGRES_PASSWORD: ${USERS_DB_PASSWORD}
      POSTGRES_DB: ${USERS_DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - users_data:/var/lib/postgresql
    networks:
      - innowise_network

  users_redis:
    container_name: users_redis
    image: redis:latest
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_DATABASE: ${REDIS_DATABASE}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - innowise_network

  order-service:
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ORDERS_DB_DATABASE: orders
      ORDERS_DB_USERNAME: orders
      ORDERS_DB_PASSWORD: orders
    depends_on:
      - order_db
    networks:
      - innowise_network

  order_db:
    container_name: order_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${ORDERS_DB_USERNAME}
      POSTGRES_PASSWORD: ${ORDERS_DB_PASSWORD}
      POSTGRES_DB: ${ORDERS_DB_DATABASE}
    ports:
      - "5434:5432"
    volumes:
      - order_data:/var/lib/postgresql
    networks:
      - innowise_network

  payment-service:
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGO_DB_DATABASE: ${MONGO_DB_DATABASE}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
    depends_on:
      - mongo_db
    networks:
      - innowise_network

  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - innowise_network

  auth-service:
    container_name: auth_service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AUTH_DB_DATABASE: secret
      AUTH_DB_USERNAME: secret
      AUTH_DB_PASSWORD: secret
    depends_on:
      - auth_db
    networks:
      - innowise_network

  auth_db:
    container_name: auth_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${AUTH_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql
    networks:
      - innowise_network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - innowise_network

volumes:
  users_data:
  auth_data:
  order_data:
  redis_data:
  mongo_data:
  mongo_config:

networks:
  innowise_network:
    driver: bridge