services:
  users_db:
    container_name: users_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${USERS_DB_USERNAME}
      POSTGRES_PASSWORD: ${USERS_DB_PASSWORD}
      POSTGRES_DB: ${USERS_DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - users_data:/var/lib/postgresql
    networks:
      - innowise_network

  auth_db:
    container_name: auth_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${AUTH_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql
    networks:
      - innowise_network

  order_db:
    container_name: order_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${ORDERS_DB_USERNAME}
      POSTGRES_PASSWORD: ${ORDERS_DB_PASSWORD}
      POSTGRES_DB: ${ORDERS_DB_DATABASE}
    ports:
      - "5434:5432"
    volumes:
      - order_data:/var/lib/postgresql
    networks:
      - innowise_network

  users_redis:
    container_name: users_redis
    image: redis:latest
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_DATABASE: ${REDIS_DATABASE}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - innowise_network

  user-service:
    container_name: user_service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      USERS_DB_HOST: localhost
      USERS_DB_DATABASE: user_db
      USERS_DB_USERNAME: postgres
      USERS_DB_PASSWORD: postgres
      REDIS_HOST: users_redis
      REDIS_DATABASE: 0
    depends_on:
      - users_db
      - users_redis
    networks:
      - innowise_network

  auth-service:
    container_name: auth_service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AUTH_DB_DATABASE: secret
      AUTH_DB_USERNAME: secret
      AUTH_DB_PASSWORD: secret
    depends_on:
      - auth_db
    networks:
      - innowise_network

volumes:
  users_data:
  auth_data:
  order_data:
  redis_data:


networks:
  innowise_network:
    driver: bridge