spring:
  application:
    name: payment-service

  mongodb:
    uri: mongodb://localhost:${MONGO_DB_PORT:27017}/${MONGO_DB_DATABASE:mongo}
    password: ${MONGO_DB_PASSWORD:mongo}
    username: ${MONGO_DB_USERNAME:mongo}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/api/v1/auth/jwks.json
  kafka:
    bootstrap-servers: localhost:9092

api:
  external:
    url: https://www.random.org/integers/?num=1&min=1&max=10000&col=1&base=10&format=plain

mongock:
  migration-scan-package: com.innowise.paymentservice.migration
  lock-acquired-for-millis: 60000
  lock-quit-trying-after-millis: 180000

server:
  port: 8083
logging:
  level:
    root: info
    org.springframework.data.mongodb: info
    org.springframework.kafka: info
