apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - db/

secretGenerator:
  - name: auth-service-credentials
    envs:
      - envs/auth-service.secret.env
  - name: auth-service-jwt-keys
    files:
      - keys/private.pem
      - keys/public.pem

configMapGenerator:
  - name: auth-service-config
    envs:
      - envs/auth-service.config.env

images:
  - name: tarantasik/auth-service
    newTag: "latest"