spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: {USERS_DB_USERNAME:postgres}
    password: {USERS_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-root.yaml
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/api/v1/auth/jwks

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms
      database: 0
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

server:
  port: 8081

logging:
  level:
    com.innowise.userservice: DEBUG
    org.springframework.web: DEBUG
    root: INFO
