apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - db/
  - cache/

secretGenerator:
  - name: user-service-credentials
    envs:
      - envs/user-service.secret.env

configMapGenerator:
  - name: user-service-config
    envs:
      - envs/user-service.config.env

images:
  - name: tarantasik/user-service
    newTag: "latest"